package com.heimdallr.monitor.common.domain.api;

public enum ErrorCode {
    OK,
    BAD_REQUEST,
    UNAUTHORIZED,
    TOKEN_EXPIRED,
    FORBIDDEN,
    MENU_FORBIDDEN,
    APP_DATA_FORBIDDEN,
    ENV_FORBIDDEN,
    SENSITIVE_FIELD_FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    VALIDATION_FAILED,
    RATE_LIMITED,
    INTERNAL_ERROR,
    APPLICATION_NOT_AUTHORIZED,
    DATA_SOURCE_UNAVAILABLE,
    METRIC_NOT_FOUND,
    METRIC_NO_RECENT_DATA,
    LOG_QUERY_TIMEOUT,
    ALERT_STATUS_CONFLICT,
    ALERT_RULE_INVALID,
    CHANNEL_TEST_FAILED,
    EXPORT_TASK_TOO_LARGE,
    SECRET_VIEW_FORBIDDEN
}
